version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "83:80"
    volumes:
      - ./web/:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./web/:/var/www/html

